### ISSUE TITLE
Trying to make an updated working version

### ISSUE THREAD

**Issue by Ivo-Balbaert** [cjcone/roctris#1]
Hi Jared, awesome project!

I wanted to make the project work again in current Roc
I had to correct  a lot of new errors because of this, but most where trivial (see attached code).
When trying to build, both cc and the legacy linker gave me:

roc --linker=legacy Roctris.roc
🔨 Rebuilding platform...
ld: platform/linux-x64.o: in function `host::execute_main':
/home/ivo/roc_repo/roctris/platform/src/lib.rs:82: undefined reference to `roc__mainForHost_size'
ld: platform/linux-x64.o: in function `host::call_the_closure':
/home/ivo/roc_repo/roctris/platform/src/lib.rs:118: undefined reference to `roc__mainForHost_1_Fx_result_size'
ld: /home/ivo/roc_repo/roctris/platform/src/lib.rs:122: undefined reference to `roc__mainForHost_1_Fx_caller'
thread 'main' panicked at 'not yet implemented: gracefully handle `ld` (or `zig` in the case of wasm with --optimize) returning exit code Some(1)', crates/compiler/build/src/program.rs:1036:17

I didn't see a solution for this, so I tried with the latest basic-cli v0.4.0, moving some of your code to its cache, causing some more strange errors.

Do you see a way to get this working again? It would be phantastic to have this beautiful project working again. Thanks!
[roctris.zip](https://github.com/jared-cone/roctris/files/12138310/roctris.zip)

**Comment by jared-cone** [comment]
Hey glad you're interested! I haven't been keeping up with Roc, but my guess is roctris's `lib.rs` needs to be updated to be similar to the latest CLI example at https://github.com/roc-lang/roc/blob/main/examples/cli/cli-platform/src/lib.rs . For example, updating the contents in the `extern "C" {...}` block, and some of the roc functions below that such as `roc_panic`

**Comment by Ivo-Balbaert** [comment]
Thanks very much! I only had to update the contents in the extern "C" block, and now it works!
